Initial Commit

diff --git a/files/nvidia/0001-Enable-in-tree-build.patch b/files/nvidia/0001-Enable-in-tree-build.patch
--- a/files/nvidia/0001-Enable-in-tree-build.patch
+++ b/files/nvidia/0001-Enable-in-tree-build.patch
@@ -1,22 +1,33 @@
-From 2654e6c8eb87a5761dd864250503e744ccee3eed Mon Sep 17 00:00:00 2001
+From 12fba22f9a96cc628a1bb0d467547b3e83b6e6ef Mon Sep 17 00:00:00 2001
 From: chlorodose <chlorodose@chlorodose.me>
-Date: Fri, 1 May 2026 21:58:44 +0800
-Subject: [PATCH] Patch build files to enable in-tree integration
+Date: Sun, 3 May 2026 15:24:11 +0800
+Subject: [PATCH] Enable in tree build
 
 ---
- copy-builtin        | 34 ++++++++++++++++++++++++++++++++++
- kernel-open/Kbuild  | 45 ++++++++++++++++++++++++++++++++++++++++++---
- kernel-open/Kconfig | 45 +++++++++++++++++++++++++++++++++++++++++++++
- 3 files changed, 121 insertions(+), 3 deletions(-)
+ .gitignore              |  1 +
+ copy-builtin            | 30 +++++++++++++++++++++++++
+ kernel-open/Kbuild      | 50 ++++++++++++++++++++++++++++++++++++-----
+ kernel-open/Kconfig     | 46 +++++++++++++++++++++++++++++++++++++
+ kernel-open/conftest.sh |  5 ++++-
+ 5 files changed, 126 insertions(+), 6 deletions(-)
  create mode 100755 copy-builtin
  create mode 100644 kernel-open/Kconfig
 
+diff --git a/.gitignore b/.gitignore
+index 75434ed..2e9be49 100644
+--- a/.gitignore
++++ b/.gitignore
+@@ -3,3 +3,4 @@
+ *.o.cmd
+ *.o.d
+ _out/
++!linux.symvers
 diff --git a/copy-builtin b/copy-builtin
 new file mode 100755
-index 0000000..8d0eda6
+index 0000000..7a53fe8
 --- /dev/null
 +++ b/copy-builtin
-@@ -0,0 +1,34 @@
+@@ -0,0 +1,30 @@
 +
 +#!/bin/sh
 +
@@ -34,32 +45,29 @@ index 0000000..8d0eda6
 +KERNEL_DIR="$(realpath "$1")"
 +cd "$(dirname "$0")"
 +
-+if [ ! -f "$KERNEL_DIR"/Module.symvers ]; then
-+    echo "Error: Module.symvers not found. Please make kernel first and then call this script" >&2
-+    exit 1
-+fi
++for F in Module.symvers vmlinux.symvers; do
++    P="$KERNEL_DIR/$F"
++    if [ -f "$P" ]; then
++        SYMVER="$P"
++    fi
++done
++cp "$SYMVER" linux.symvers
 +
-+cp -r . "$KERNEL_DIR"/drivers/video/nvidia
++cp -r . "$KERNEL_DIR"/drivers/video/nvidia && rm -rf "$KERNEL_DIR"/drivers/video/nvidia/.git
 +printf '!.*\n!*\n' | cat - .gitignore >"$KERNEL_DIR"/drivers/video/nvidia/.gitignore
-+echo '!conftest/' >>"$KERNEL_DIR"/drivers/video/nvidia/kernel-open/.gitignore
 +
 +sed -i '/source "drivers\/gpu\/nova-core\/Kconfig"/a source "drivers/video/nvidia/kernel-open/Kconfig"' "$KERNEL_DIR"/drivers/video/Kconfig
 +echo 'obj-$(CONFIG_NVIDIA)		  += nvidia/kernel-open/' >> "$KERNEL_DIR"/drivers/video/Makefile
-+
-+cd "$KERNEL_DIR"
-+./scripts/config \
-+    --module NVIDIA --module NVIDIA_MODESET --module NVIDIA_DRM --module NVIDIA_UVM --module NVIDIA_PEERMEM
-+make olddefconfig
-+make drivers/video/nvidia/kernel-open/conftest/.all-conftests.o $MAKEOPTS
 diff --git a/kernel-open/Kbuild b/kernel-open/Kbuild
-index 089c77d..4440c84 100644
+index 089c77d..83c5886 100644
 --- a/kernel-open/Kbuild
 +++ b/kernel-open/Kbuild
-@@ -2,6 +2,32 @@
+@@ -2,6 +2,33 @@
  # Kbuild file for NVIDIA Linux GPU driver kernel modules
  ###########################################################################
  
 +export IGNORE_MISSING_MODULE_SYMVERS := 1
++export IGNORE_CC_MISMATCH := 1
 +NV_KERNEL_SOURCES   := $(shell realpath "$(srctree)")
 +NV_KERNEL_OUTPUT    := $(shell realpath "$(objtree)")
 +NV_SPECTRE_V2       := 0
@@ -88,7 +96,7 @@ index 089c77d..4440c84 100644
  #
  # The parent makefile is expected to define:
  #
-@@ -75,8 +101,8 @@ $(foreach _module, $(NV_KERNEL_MODULES), \
+@@ -75,8 +102,8 @@ $(foreach _module, $(NV_KERNEL_MODULES), \
   $(eval include $(src)/$(_module)/$(_module).Kbuild))
  
  
@@ -99,15 +107,26 @@ index 089c77d..4440c84 100644
  ccflags-y += -Wall $(DEFINES) $(INCLUDES) -Wno-cast-qual -Wno-format-extra-args
  ccflags-y += -D__KERNEL__ -DMODULE -DNVRM
  ccflags-y += -DNV_VERSION_STRING=\"595.71.05\"
-@@ -268,7 +294,6 @@ $(foreach header,$(NV_HEADER_PRESENCE_TESTS),$(eval $(call NV_HEADER_PRESENCE_CH
+@@ -210,7 +237,7 @@ NV_CONFTEST_HEADERS += $(NV_CONFTEST_COMPILE_TEST_HEADERS)
+ $(obj)/conftest/compile-tests/%.h: $(NV_CONFTEST_SCRIPT) $(NV_CONFTEST_HEADER)
+ 	@mkdir -p $(obj)/conftest/compile-tests
+ 	@echo " CONFTEST: $(notdir $*)"
+-	@$(NV_CONFTEST_CMD) compile_tests '$(NV_CONFTEST_CFLAGS)' \
++	@MODULE_SYMVERS_PATHS="$(realpath $(obj)/../linux.symvers)" $(NV_CONFTEST_CMD) compile_tests '$(NV_CONFTEST_CFLAGS)' \
+ 	 $(notdir $*) > $@
+ 
+ #
+@@ -268,8 +295,7 @@ $(foreach header,$(NV_HEADER_PRESENCE_TESTS),$(eval $(call NV_HEADER_PRESENCE_CH
  $(obj)/conftest/headers.h: $(call NV_HEADER_PRESENCE_PART,$(NV_HEADER_PRESENCE_TESTS))
  	@cat $^ > $@
  
 -clean-dirs := $(obj)/conftest
- 
+-
++clean-files += conftest nv_compiler.h
  
  # For any object files that depend on conftest, declare the dependency here.
-@@ -305,3 +330,17 @@ $(obj)/conftest/uts_release: NV_GENERATE_UTS_RELEASE
+ $(addprefix $(obj)/,$(NV_OBJECTS_DEPEND_ON_CONFTEST)): | $(NV_CONFTEST_HEADERS)
+@@ -305,3 +331,17 @@ $(obj)/conftest/uts_release: NV_GENERATE_UTS_RELEASE
  .PHONY: NV_GENERATE_UTS_RELEASE
  
  $(NV_CONFTEST_HEADERS): $(obj)/conftest/uts_release
@@ -115,22 +134,22 @@ index 089c77d..4440c84 100644
 +$(obj)/conftest/.all-conftests.o: $(NV_CONFTEST_HEADERS)
 +
 +$(obj)/nvidia/nv-kernel.o_binary: $(NV_CONFTEST_HEADERS)
-+	$(MAKE) -C "$(src)/.." kernel-open/nvidia/nv-kernel.o_binary
++	@$(MAKE) -C "$(src)/.." kernel-open/nvidia/nv-kernel.o_binary
 +	@if [ -z "$(NV_INTREE_BUILD)" ]; then \
 +		ln -s "$(src)/nvidia/nv-kernel.o_binary" "$(obj)/nvidia/nv-kernel.o_binary" ;\
 +	fi
 +
 +$(obj)/nvidia-modeset/nv-modeset-kernel.o_binary: $(NV_CONFTEST_HEADERS)
-+	$(MAKE) -C "$(src)/.." kernel-open/nvidia-modeset/nv-modeset-kernel.o_binary
++	@$(MAKE) -C "$(src)/.." kernel-open/nvidia-modeset/nv-modeset-kernel.o_binary
 +	@if [ -z "$(NV_INTREE_BUILD)" ]; then \
 +	    ln -s "$(src)/nvidia-modeset/nv-modeset-kernel.o_binary" "$(obj)/nvidia-modeset/nv-modeset-kernel.o_binary" ;\
 +	fi
 diff --git a/kernel-open/Kconfig b/kernel-open/Kconfig
 new file mode 100644
-index 0000000..4138555
+index 0000000..23119d7
 --- /dev/null
 +++ b/kernel-open/Kconfig
-@@ -0,0 +1,45 @@
+@@ -0,0 +1,46 @@
 +config NVIDIA
 +    tristate "NVIDIA GPU opensource driver (GSP RM)"
 +    depends on m
@@ -172,10 +191,34 @@ index 0000000..4138555
 +config NVIDIA_PEERMEM
 +    tristate "NVIDIA GPU opensource driver - PEERMEM"
 +    depends on NVIDIA
++    depends on DEVICE_PRIVATE
 +    help
 +      NVIDIA Peer-to-Peer memory support (nvidia-peermem.ko).
 +      Allows third-party devices (like InfiniBand NICs) to directly access
 +      GPU memory via RDMA.
+diff --git a/kernel-open/conftest.sh b/kernel-open/conftest.sh
+index cb4da27..5a84fc2 100755
+--- a/kernel-open/conftest.sh
++++ b/kernel-open/conftest.sh
+@@ -15,7 +15,6 @@ XEN_PRESENT=1
+ PREEMPT_RT_PRESENT=0
+ 
+ NVIDIA_OOT_PATH="/usr/src/nvidia/nvidia-public"
+-MODULE_SYMVERS_PATHS="$OUTPUT/Module.symvers"
+ 
+ # Also search in out-of-tree Module.symvers on Tegra
+ if [ -d ${NVIDIA_OOT_PATH} ]; then
+@@ -335,6 +334,10 @@ check_symbol_exists() {
+     TAB='	'
+ 
+     if [ ${OS_FREEBSD} -ne 1 ] ; then
++        if [ ! -f "$MODULE_SYMVERS_PATHS" ]; then
++            echo "Symvers file not found" >&2
++            exit 1
++        fi
+         # Linux:
+         # ------
+         #
 -- 
 2.52.0
 
